### ISSUE TITLE
Seemingly unrelated errors

### ISSUE THREAD

**Issue by NAndreasson** [NAndreasson/cowl#1]
I'm a bit puzzled about some errors I get at times when building Firefox. For example, when I added LabeledObjects I got the following error in a file which seems unrelated to my changes:

```
:16.94 In file included from /Users/nandreasson/Code/gecko-dev/cowl/obj-debug/dom/base/Unified_cpp_dom_base6.cpp:128:
 2:16.95 /Users/nandreasson/Code/gecko-dev/cowl/dom/base/nsJSTimeoutHandler.cpp:39:28: error: reference to 'Function' is ambiguous
 2:16.95                            Function& aFunction,
 2:16.95                            ^
 2:16.95 /Users/nandreasson/Code/gecko-dev/cowl/obj-debug/dist/include/mozilla/Function.h:129:7: note: candidate found by name lookup is 'mozilla::Function'
 2:16.95 class Function;
```

It has been suggested to me that these types of errors could be caused by the "unified build system" where adding files changes the order of the chunks and so on. 

I resolved it by changing nsJSTimeoutHandler to use `mozilla::dom::Function` instead of just `Function` - see https://github.com/NAndreasson/cowl/commit/e7edd24ede35e92ec88dd44f4e4d0fe5b79847c4. However, I'm thinking that these type of changes should not be needed,  and it would be optimal to not touch unrelated files.

**Comment by NAndreasson** [comment]
When I moved the COWL principal parser to a file of its own I had to introduce some changes as well. 

It might be possible to solve some of these problems with forward declaration instead.

**Comment by deian** [comment]
Unfortunately we may have to create a separate bug to land e7edd24. But maybe the name clash arises because of something you introduced?

These kinds of issues arise since the header files are basically concatenated together. So naming becomes more challenging when things are not fully qualified.
